In [58]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

In [59]:
# Loaded the resampled data
x_train = np.load('../data/x_train_resampled.npy')
y_train = np.load('../data/y_train_resampled.npy')
x_test = np.load('../data/x_test.npy')
y_test = np.load('../data/y_test.npy')

print("Ready to train! Resampled dataset loaded")

Ready to train! Resampled dataset loaded


In [60]:
# Implemented the Logistic Regression and predicted and checked the results on it 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(x_train,y_train)
y_pred = lr_model.predict(x_test)

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test,y_pred))

print("=== Classification Report ===")
print(classification_report(y_test,y_pred))



=== Confusion Matrix ===
[[55425  1439]
 [    8    90]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       1.00      0.97      0.99     56864
           1       0.06      0.92      0.11        98

    accuracy                           0.97     56962
   macro avg       0.53      0.95      0.55     56962
weighted avg       1.00      0.97      0.99     56962



In [61]:
# Fine Tuning the logistics regression algrothim model by playing with the threshold
from sklearn.metrics import recall_score, precision_score

y_probs = lr_model.predict_proba(x_test)[:,1]
thresholds = [0.3,0.5,0.7,0.9]

print(f"{'Threshold':<12} | {'Precision':<10} | {'Recall':<10}")
print("-"*35)

for t in thresholds:
    y_pred_t = (y_probs>= t).astype(int)

    p = precision_score(y_test,y_pred_t)
    r = recall_score(y_test,y_pred_t)

    print(f"{t:<12} | {p:<10.4f} | {r:<10.4f}")


Threshold    | Precision  | Recall    
-----------------------------------
0.3          | 0.0283     | 0.9184    
0.5          | 0.0589     | 0.9184    
0.7          | 0.1065     | 0.8980    
0.9          | 0.1977     | 0.8878    


In [62]:
# Implemented Random Forest Classifier and evaluated the results
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

rf_model = RandomForestClassifier(n_estimators=50,random_state=42,n_jobs=-1) 

rf_model.fit(x_train,y_train)
y_pred_rf = rf_model.predict(x_test)

print("=== Confusion Matrix")
print(confusion_matrix(y_test,y_pred_rf))

print("===Classification Report===")
print(classification_report(y_test,y_pred_rf))

=== Confusion Matrix
[[56851    13]
 [   18    80]]
===Classification Report===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.86      0.82      0.84        98

    accuracy                           1.00     56962
   macro avg       0.93      0.91      0.92     56962
weighted avg       1.00      1.00      1.00     56962



In [63]:
# Fine tuning Random Forest by changing prediction threshold

y_probs_rf = rf_model.predict_proba(x_test)[:,1]

thresholds = [0.3,0.5,0.7,0.9]
for thresholds in thresholds:
    y_pred_threshold_rf = (y_probs_rf>=thresholds).astype(int)

    print(f"\nThreshold: {thresholds}")
    print(f"Recall:", recall_score(y_test,y_pred_threshold_rf))
    print(f"Precision:", precision_score(y_test,y_pred_threshold_rf))
    print(f"confusion_matrix:")
    print(confusion_matrix(y_test,y_pred_threshold_rf))


Threshold: 0.3
Recall: 0.8877551020408163
Precision: 0.7310924369747899
confusion_matrix:
[[56832    32]
 [   11    87]]

Threshold: 0.5
Recall: 0.826530612244898
Precision: 0.8526315789473684
confusion_matrix:
[[56850    14]
 [   17    81]]

Threshold: 0.7
Recall: 0.7755102040816326
Precision: 0.95
confusion_matrix:
[[56860     4]
 [   22    76]]

Threshold: 0.9
Recall: 0.6632653061224489
Precision: 0.9701492537313433
confusion_matrix:
[[56862     2]
 [   33    65]]


In [64]:
!pip install xgboost


Defaulting to user installation because normal site-packages is not writeable


In [69]:
# Implementing the XGBoost algorithm and evaluated the results
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, classification_report

xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=42, n_jobs=-1)

xgb_model.fit(x_train, y_train)

y_pred_xgb = xgb_model.predict(x_test)

print("=== XGBoost Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred_xgb))

print("\n=== XGBoost Classification Report ===")
print(classification_report(y_test, y_pred_xgb))

=== XGBoost Confusion Matrix ===
[[56700   164]
 [   13    85]]

=== XGBoost Classification Report ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.34      0.87      0.49        98

    accuracy                           1.00     56962
   macro avg       0.67      0.93      0.74     56962
weighted avg       1.00      1.00      1.00     56962



In [ ]:
# Saving the model using pickle
 

with open("../models/fraud_model.pkl", "wb") as file:
    pickle.dump(rf_model, file)

print("Random Forest model saved successfully!")


Random Forest model saved successfully!
